name: "Application observability for AWS Action"
description: "Support Agentic AI–driven performance investigation and resolution using live production telemetry."
branding:
  icon: "cloud"
  color: "orange"

inputs:
  bot_name:
    description: "The bot name to respond to in comments (e.g., @awsapm)"
    required: false
    default: "@awsapm"
  target_branch:
    description: "The branch to merge PRs into (defaults to repository default branch)"
    required: false
  branch_prefix:
    description: "Prefix for branches created by the action (e.g., 'awsapm/', 'awsapm-')"
    required: false
    default: "awsapm/"
  allowed_non_write_users:
    description: "Comma-separated list of GitHub usernames allowed to use this action even without write access. Empty string (default) means only users with write/admin access can use it."
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for API calls. If not provided, uses the default GitHub Actions token."
    required: false
    default: ${{ github.token }}
  custom_prompt:
    description: "Custom instructions to guide the AI agent's analysis and actions"
    required: false
    default: ""
  cli_tool:
    description: "CLI tool to use for investigation (claude_code)"
    required: false
    default: "claude_code"
  output_file:
    description: "Path to AI agent execution output file (used to post results back to GitHub). For claude_code path, pass this from claude-code-base-action outputs in a second call to this action."
    required: false
  output_status:
    description: "Execution status from AI agent (success or failure). Only used when output_file is provided."
    required: false
  comment_id:
    description: "GitHub comment ID to update with results (only for claude_code path when posting results). Pass this from the first call's awsapm_comment_id output."
    required: false
  enable_cloudwatch_mcp:
    description: "Enable CloudWatch MCP server for metrics, alarms, and log insights"
    required: false
    default: "true"

outputs:
  # Preparation outputs for claude-code-base-action
  prompt_file:
    description: "Path to the generated prompt file for claude-code-base-action"
    value: ${{ steps.prepare-claude.outputs.prompt_file }}
  mcp_config_file:
    description: "Path to the MCP servers configuration JSON file"
    value: ${{ steps.prepare-claude.outputs.mcp_config_file }}
  allowed_tools:
    description: "Comma-separated list of allowed tools"
    value: ${{ steps.prepare-claude.outputs.allowed_tools }}

  # Common outputs
  awsapm_comment_id:
    description: "GitHub comment ID for tracking the investigation"
    value: ${{ steps.init.outputs.awsapm_comment_id }}
  branch_name:
    description: "The branch created by Application observability for AWS Action for this execution"
    value: ${{ steps.init.outputs.AWSAPM_BRANCH }}
  github_token:
    description: "The GitHub token used by the action"
    value: ${{ steps.init.outputs.GITHUB_TOKEN }}

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        npm install

    - name: Init action
      id: init
      if: inputs.output_file == ''  # Skip init when posting results
      shell: bash
      run: |
        node ${GITHUB_ACTION_PATH}/src/init.js
      env:
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        BOT_NAME: ${{ inputs.bot_name }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        OVERRIDE_GITHUB_TOKEN: ${{ inputs.github_token }}
        ALLOWED_NON_WRITE_USERS: ${{ inputs.allowed_non_write_users }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        DEFAULT_WORKFLOW_TOKEN: ${{ github.token }}

    # Install MCP Tools for claude-code-base-action
    - name: Install MCP Tools
      if: steps.init.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        set -e  # Exit immediately if any command fails

        # Install uv/uvx for MCP server execution
        echo "Installing uv package manager for MCP server support..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

        # Verify uvx installation
        if ! command -v uvx &> /dev/null; then
          echo "::error::uvx installation failed - MCP tools will not work"
          exit 1
        fi
        echo "uvx installed successfully"
        uvx --version

    - name: Prepare Claude Configuration
      id: prepare-claude
      if: steps.init.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        node src/prepare-claude-config.js
      env:
        GITHUB_TOKEN: ${{ steps.init.outputs.GITHUB_TOKEN }}
        ENABLE_CLOUDWATCH_MCP: ${{ inputs.enable_cloudwatch_mcp }}
        INPUT_PROMPT_FILE: ${{ runner.temp }}/awsapm-prompts/awsapm-prompt.txt
        OUTPUT_DIR: ${{ runner.temp }}/awsapm-prompts

    # Post results (when output_file is provided)
    - name: Post Investigation Results
      if: inputs.output_file != '' && inputs.comment_id != ''
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        node src/post-claude-result.js
      env:
        AWSAPM_COMMENT_ID: ${{ inputs.comment_id }}
        CLAUDE_EXECUTION_FILE: ${{ inputs.output_file }}
        CLAUDE_CONCLUSION: ${{ inputs.output_status }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_RUN_ID: ${{ github.run_id }}