name: "Application observability for AWS Action"
description: "Provides Agentic AI–driven performance investigation and resolution using live production telemetry."
branding:
  icon: "cloud"
  color: "orange"

inputs:
  bot_name:
    description: "The bot name to respond to in comments (e.g., @awsapm)"
    required: false
    default: "@awsapm"
  target_branch:
    description: "The branch to merge PRs into (defaults to repository default branch)"
    required: false
  branch_prefix:
    description: "Prefix for branches created by the action (e.g., 'awsapm/', 'awsapm-')"
    required: false
    default: "awsapm/"
  allowed_non_write_users:
    description: "Comma-separated list of GitHub usernames allowed to use this action even without write access. Empty string (default) means only users with write/admin access can use it."
    required: false
    default: ""
  github_token:
    description: "GitHub token to use for API calls. If not provided, uses the default GitHub Actions token."
    required: false
    default: ${{ github.token }}
  custom_prompt:
    description: "Custom instructions to guide the AI agent's analysis and actions"
    required: false
    default: ""
  cli_tool:
    description: "CLI tool to use for investigation (amazon_q_cli or claude_code)"
    required: true
  cli_tool_oauth_token:
    description: "OAuth token for the selected CLI tool (required when cli_tool is claude_code)"
    required: false
  enable_cloudwatch_mcp:
    description: "Enable CloudWatch MCP server for metrics, alarms, and log insights"
    required: false
    default: "true"

outputs:
  execution_file:
    description: "Path to the AI agent tool execution output file"
    value: ${{ steps.aws-apm-cli.outputs.execution_file }}
  branch_name:
    description: "The branch created by Application observability for AWS Action for this execution"
    value: ${{ steps.init.outputs.AWSAPM_BRANCH }}
  github_token:
    description: "The GitHub token used by the action"
    value: ${{ steps.init.outputs.GITHUB_TOKEN }}

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        npm install

    - name: Init action
      id: init
      shell: bash
      run: |
        node ${GITHUB_ACTION_PATH}/src/init.js
      env:
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        BOT_NAME: ${{ inputs.bot_name }}
        TARGET_BRANCH: ${{ inputs.target_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
        OVERRIDE_GITHUB_TOKEN: ${{ inputs.github_token }}
        ALLOWED_NON_WRITE_USERS: ${{ inputs.allowed_non_write_users }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        DEFAULT_WORKFLOW_TOKEN: ${{ github.token }}

    - name: Install CLI Tools
      if: steps.init.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        set -e  # Exit immediately if any command fails

        # Install uv/uvx for MCP server execution
        echo "Installing uv package manager for MCP server support..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

        # Verify uvx installation
        if ! command -v uvx &> /dev/null; then
          echo "::error::uvx installation failed - MCP tools will not work"
          exit 1
        fi
        echo "uvx installed successfully"
        uvx --version

        if [ "${{ inputs.cli_tool }}" = "claude_code" ]; then
          echo "Installing Claude Code CLI..."
          curl -fsSL https://claude.ai/install.sh | bash -s 1.0.117
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

          # Verify Claude CLI installation
          if ! command -v claude &> /dev/null; then
            echo "::error::Claude Code CLI installation failed - claude command not found in PATH"
            exit 1
          fi
          echo "Claude Code CLI installed successfully"
          claude --version
        elif [ "${{ inputs.cli_tool }}" = "amazon_q_cli" ]; then
          echo "Installing Amazon Q Developer CLI..."
          sudo apt-get update
          curl -L -o amazon-q.deb https://desktop-release.q.us-east-1.amazonaws.com/1.19.4/amazon-q.deb
          sudo apt-get install -y --fix-missing ./amazon-q.deb || sudo apt-get install -y -f

          # Verify Amazon Q CLI installation
          if ! command -v q &> /dev/null; then
            echo "::error::Amazon Q CLI installation failed - q command not found in PATH"
            exit 1
          fi
          echo "Amazon Q CLI installed successfully"
          q --version
        else
          echo "::error::Invalid cli_tool value: ${{ inputs.cli_tool }}. Must be 'amazon_q_cli' or 'claude_code'"
          exit 1
        fi
        

    - name: Run Application observability for AWS Investigation
      id: aws-apm-cli
      if: steps.init.outputs.contains_trigger == 'true'
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        node src/execute.js
      env:
        GITHUB_TOKEN: ${{ steps.init.outputs.GITHUB_TOKEN }}
        CLI_TOOL: ${{ inputs.cli_tool }}
        CLI_TOOL_OAUTH_TOKEN: ${{ inputs.cli_tool_oauth_token }}
        ENABLE_CLOUDWATCH_MCP: ${{ inputs.enable_cloudwatch_mcp }}
        INPUT_PROMPT_FILE: ${{ runner.temp }}/awsapm-prompts/awsapm-prompt.txt

    - name: Update comment with results
      if: steps.init.outputs.contains_trigger == 'true' && steps.init.outputs.awsapm_comment_id && always()
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        node src/post-result.js
      env:
        REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        AWSAPM_COMMENT_ID: ${{ steps.init.outputs.awsapm_comment_id }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_TOKEN: ${{ steps.init.outputs.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        TRIGGER_COMMENT_ID: ${{ github.event.comment.id }}
        AWSAPM_BRANCH: ${{ steps.init.outputs.AWSAPM_BRANCH }}
        IS_PR: ${{ github.event.issue.pull_request != null || github.event_name == 'pull_request_review_comment' }}
        TARGET_BRANCH: ${{ steps.init.outputs.TARGET_BRANCH }}
        AWSAPM_SUCCESS: ${{ steps.aws-apm-cli.outputs.conclusion == 'success' }}
        OUTPUT_FILE: ${{ steps.aws-apm-cli.outputs.execution_file || '' }}
        TRIGGER_USERNAME: ${{ github.event.comment.user.login || github.event.issue.user.login || github.event.pull_request.user.login || github.event.sender.login || github.triggering_actor || github.actor || '' }}
        INIT_SUCCESS: ${{ steps.init.outcome == 'success' }}